// GENERATED by scripts/gen_icon_font.py - do not edit by hand.
// Font Awesome 6.5.2 Free Solid, subset to the glyphs this interface draws.
// Font: SIL OFL 1.1. Icons: CC BY 4.0. See third_party/fontawesome/LICENSE.txt.
#pragma once

#include "imgui.h"

namespace scrt::viz {

/// The subset TTF, compiled in. Not a file on disk: an embedded asset cannot be
/// left out of a package the way the example meshes once were.
extern const unsigned char kIconFontTTF[];
/// Length of kIconFontTTF in bytes.
extern const unsigned int kIconFontTTFLen;

/// Inclusive codepoint range of the subset, for ImFontConfig::GlyphRanges.
constexpr ImWchar kIconMin = 0xe2ca;
constexpr ImWchar kIconMax = 0xf5fd;

} // namespace scrt::viz

// Icon literals. Each is a UTF-8 string, so it concatenates with ordinary text:
//     ImGui::Button(ICON_FA_PLAY "  Trace")

// Top bar and chrome
#define ICON_FA_SUN "\xef\x86\x85"  // U+f185
#define ICON_FA_MOON "\xef\x86\x86"  // U+f186
#define ICON_FA_GEAR "\xef\x80\x93"  // U+f013
#define ICON_FA_USER "\xef\x80\x87"  // U+f007
#define ICON_FA_CIRCLE_INFO "\xef\x81\x9a"  // U+f05a
#define ICON_FA_TRIANGLE_EXCLAMATION "\xef\x81\xb1"  // U+f071
#define ICON_FA_CHEVRON_RIGHT "\xef\x81\x94"  // U+f054
#define ICON_FA_CHEVRON_DOWN "\xef\x81\xb8"  // U+f078
#define ICON_FA_XMARK "\xef\x80\x8d"  // U+f00d
#define ICON_FA_CHECK "\xef\x80\x8c"  // U+f00c
#define ICON_FA_TRASH "\xef\x87\xb8"  // U+f1f8

// Files
#define ICON_FA_FILE "\xef\x85\x9b"  // U+f15b
#define ICON_FA_FILE_IMPORT "\xef\x95\xaf"  // U+f56f
#define ICON_FA_FILE_EXPORT "\xef\x95\xae"  // U+f56e
#define ICON_FA_FOLDER_OPEN "\xef\x81\xbc"  // U+f07c
#define ICON_FA_FLOPPY_DISK "\xef\x83\x87"  // U+f0c7
#define ICON_FA_ARROW_ROTATE_LEFT "\xef\x83\xa2"  // U+f0e2
#define ICON_FA_RIGHT_LEFT "\xef\x8d\xa2"  // U+f362

// Scene tree
#define ICON_FA_CUBE "\xef\x86\xb2"  // U+f1b2
#define ICON_FA_LAYER_GROUP "\xef\x97\xbd"  // U+f5fd
#define ICON_FA_SOLAR_PANEL "\xef\x96\xba"  // U+f5ba
#define ICON_FA_MOUNTAIN_SUN "\xee\x94\xaf"  // U+e52f
#define ICON_FA_BOWL_FOOD "\xee\x93\x86"  // U+e4c6
#define ICON_FA_FIRE "\xef\x81\xad"  // U+f06d
#define ICON_FA_LIGHTBULB "\xef\x83\xab"  // U+f0eb
#define ICON_FA_PALETTE "\xef\x94\xbf"  // U+f53f
#define ICON_FA_SQUARE "\xef\x83\x88"  // U+f0c8
#define ICON_FA_EYE "\xef\x81\xae"  // U+f06e
#define ICON_FA_EYE_SLASH "\xef\x81\xb0"  // U+f070

// Transform tools
#define ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT "\xef\x81\x87"  // U+f047
#define ICON_FA_ROTATE "\xef\x8b\xb1"  // U+f2f1
#define ICON_FA_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER "\xef\x90\xa4"  // U+f424
#define ICON_FA_LOCK "\xef\x80\xa3"  // U+f023
#define ICON_FA_LOCK_OPEN "\xef\x8f\x81"  // U+f3c1
#define ICON_FA_CROSSHAIRS "\xef\x81\x9b"  // U+f05b
#define ICON_FA_SLIDERS "\xef\x87\x9e"  // U+f1de
#define ICON_FA_EXPAND "\xef\x81\xa5"  // U+f065
#define ICON_FA_COMPRESS "\xef\x81\xa6"  // U+f066
#define ICON_FA_ARROWS_LEFT_RIGHT "\xef\x81\xbe"  // U+f07e

// Trace and analysis
#define ICON_FA_PLAY "\xef\x81\x8b"  // U+f04b
#define ICON_FA_STOP "\xef\x81\x8d"  // U+f04d
#define ICON_FA_CHART_SIMPLE "\xee\x91\xb3"  // U+e473
#define ICON_FA_CHART_AREA "\xef\x87\xbe"  // U+f1fe
#define ICON_FA_TEMPERATURE_HALF "\xef\x8b\x89"  // U+f2c9
#define ICON_FA_MAGNIFYING_GLASS "\xef\x80\x82"  // U+f002
#define ICON_FA_DIAGRAM_PROJECT "\xef\x95\x82"  // U+f542

// Assistant
#define ICON_FA_WAND_MAGIC_SPARKLES "\xee\x8b\x8a"  // U+e2ca
